import socket
from Crypto.Cipher import DES

PORT = 5002
BLOCK_SIZE = 8


def pkcs5_unpad(data):
    """
    Remove PKCS#5 padding added by the sender.
    """
    padding_length = data[-1]

    if padding_length < 1 or padding_length > BLOCK_SIZE:
        raise ValueError("Invalid padding.")

    return data[:-padding_length]


def main():
    print("=== DES Receiver ===\n")

    # Same DES key generated by VM1
    key_hex = input("Enter shared DES Key (Hex): ").strip()

    try:
        key_bytes = bytes.fromhex(key_hex)
    except ValueError:
        print("Invalid hexadecimal key.")
        return

    if len(key_bytes) != 8:
        print("DES key must be exactly 8 bytes (16 hexadecimal characters).")
        return

    print(f"\nWaiting for connection on port {PORT}...")

    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as server:

        server.setsockopt(
            socket.SOL_SOCKET,
            socket.SO_REUSEADDR,
            1
        )

        server.bind(("0.0.0.0", PORT))
        server.listen(1)

        conn, addr = server.accept()

        with conn:
            print(
                f"\nConnected by: "
                f"{addr[0]}:{addr[1]}"
            )

            chunks = []

            while True:
                data = conn.recv(4096)

                if not data:
                    break

                chunks.append(data)

            ciphertext = b"".join(chunks)

    print("\n--- DES Decryption ---")

    print("Received Ciphertext (Hex):")
    print(ciphertext.hex().upper())

    print("\nDES Key (Hex):")
    print(key_hex.upper())

    # DES ECB decryption
    cipher = DES.new(
        key_bytes,
        DES.MODE_ECB
    )

    padded_plaintext = cipher.decrypt(ciphertext)

    try:
        plaintext_bytes = pkcs5_unpad(
            padded_plaintext
        )

        plaintext = plaintext_bytes.decode(
            "utf-8"
        )

    except Exception as error:
        print(
            f"\nDecryption/unpadding error: {error}"
        )
        return

    print("\nDecrypted Message:")
    print(plaintext)


if __name__ == "__main__":
    main()